### PR TITLE
Improve rooms

### LINKED ISSUE #8: Content for rooms page
Write up comparison table and descriptions for the rooms page.

### PR DESCRIPTION
**Pull request by quantumLeaf**
fixes #8

### CODE REVIEW

**Comment by danprince** [comment]
@quantumLeaf PR contains 3 unrelated commits. Make sure you checkout your feature branches from master, not from whichever branch you were working on before you started.

**Comment by quantumLeaf** [comment]
should be good now, but lets see

**Comment by danprince** [comment]
@quantumLeaf 
Now contains the correct commit, but it's definitely not finished. Needs a lot more work before we can merge it. The content on this page should be complete (minus the photos).

**Comment by quantumLeaf** [comment]
added more data to collums. some style stuff now broken

**Comment by danprince** [comment]
Just a small typo at [line 39](https://github.com/AstralDynamics/www-little-dream/commit/fd9c45164eea879a0ef8c72a1114d87a95deffb2#diff-71fc311f88c3ccaacf8b918294e66fc0R39).

`<//div>` should be `</div>`.

Fix it then we'll get this merged.

**Pull request merged**
