### PR TITLE
Feature/website description

### LINKED ISSUE #22: Write a website description
Write a description paragraph for the website inside `_config.yml`. This will show up along with the website name in Google. Should be super clear and punchy.

### PR DESCRIPTION
**Pull request by quantumLeaf**
fixes #22

### CODE REVIEW

**Comment by danprince** [comment]
@quantumLeaf 

> Come here to relax ... or as a base to ...

This doesn't really make grammatical sense. Swap the two clauses around to see.

> Come here as a base ... or to relax ...

 A better wording might be:

> Come here to relax ... or make it your base for ...

**Comment by quantumLeaf** [comment]
@dan now updated

**Comment by danprince** [comment]
@quantumLeaf  Same issue.

> Come here to relax in peace with only the sounds of the birds, or as a base from which to visit attractions in the surrounding area.

Swap the clauses around _or_ to check that they work.

> Come here [as a base from which to visit attractions in the surrounding area] or [to relax in peace with only the sounds of the birds]

A person can come here and _use it as a base_, but they can't come here _as a base_ themselves. If properly re-writing the English is something we're selling here, then we gotta crack down on these things.

**Comment by danprince** [comment]
This branch has also got a number of unrelated commits in. You only want 778dd1b4fd2dfc5248e92a1cd251da0571a617c2

**Comment by danprince** [comment]
Just need to fix the grammar then we'll merge it.

**Comment by quantumLeaf** [comment]
changed it to "or as a base from which to visit attractions in the surrounding area"

should be fine for now.

**Comment by danprince** [comment]
It's not getting into master until it makes sense. This is the description which will show up in Google. Last time I'm going to copy and paste this:

---

> Come here to relax in peace with only the sounds of the birds, or as a base from which to visit attractions in the surrounding area.

Swap the clauses around _or_ to check that they work.

> Come here [as a base from which to visit attractions in the surrounding area] or [to relax in peace with only the sounds of the birds]

A person can come here and use it as a base, but they can't come here as a base themselves. If properly re-writing the English is something we're selling here, then we gotta crack down on these things.

**Comment by quantumLeaf** [comment]
point taken.

**Pull request closed without merging**
